
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 18 21:19:37 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 40;
  public static final int LBRACKET = 14;
  public static final int INCREMENT = 38;
  public static final int CONST = 13;
  public static final int GE = 30;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 23;
  public static final int DECREMENT = 39;
  public static final int MINUS = 34;
  public static final int CHARACTER = 44;
  public static final int RPAREN = 7;
  public static final int AND = 25;
  public static final int LT = 31;
  public static final int OR = 26;
  public static final int COMMA = 10;
  public static final int CLASS = 17;
  public static final int DIV = 36;
  public static final int PLUS = 33;
  public static final int IF = 19;
  public static final int DOT = 16;
  public static final int LE = 32;
  public static final int BOOLEAN = 45;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 15;
  public static final int EQUAL = 8;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 35;
  public static final int NUMBER = 43;
  public static final int MOD = 37;
  public static final int NEQ = 28;
  public static final int IDENT = 42;
  public static final int BREAK = 22;
  public static final int VOID = 12;
  public static final int EQ = 27;
  public static final int ARROW = 41;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int READ = 24;
  public static final int WHILE = 21;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int GT = 29;
  public static final int PRINT = 11;
}

